### ISSUE TITLE
System.NullReferenceException at Open_Rails_Code_Bot.GitHub.Query.GetTeamMembers

### ISSUE THREAD

**Issue by twpol** [openrails/openrails-code-bot#40]
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Open_Rails_Code_Bot.GitHub.Query.GetTeamMembers(String organization, String team) in C:\Jenkins\jobs\Open Rails Code Bot (Unstable)\workspace\GitHub\Query.cs:line 54
   at Open_Rails_Code_Bot.Program.AsyncMain(IConfigurationRoot config) in C:\Jenkins\jobs\Open Rails Code Bot (Unstable)\workspace\Program.cs:line 53
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Open_Rails_Code_Bot.Program.Main(String[] args) in C:\Jenkins\jobs\Open Rails Code Bot (Unstable)\workspace\Program.cs:line 31
```

**Comment by twpol** [comment]
This is not an issue with the code, but rather GitHub has flagged the @openrails-bot account for unknown reasons. I have opened a support ticket.

**Comment by twpol** [comment]
GitHub support has apologised and unflagged the @openrails-bot account, so the Unstable Version is updating properly again.
